name: Issue triage

on:
  issues:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Add bug label
        if: contains(github.event.issue.body, 'bug')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bug

      - name: Add feature label
        if: contains(github.event.issue.body, 'feature')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: feature

      - name: Add default label
        if: |
          !contains(github.event.issue.body, 'bug') &&
          !contains(github.event.issue.body, 'feature')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: needs-triage